/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    void main() {
        Retangulo retangulo = new Retangulo("UTF-8", 12, 18);

        System.out.println(retangulo.toString());
    }
}
