/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;
import java.util.Random;

public class App {
    void main(){
        String[][] matriz = new String[9][9];

        int asteriscos = 0;

        Random r = new Random();

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                int linha = r.nextInt(0, 9);
                int coluna = r.nextInt(0, 9);

                if(matriz[i][j] == matriz[linha][coluna] && asteriscos < 10){
                    matriz[i][j] = "*";
                    asteriscos++;
                } else {
                    matriz[i][j] = ".";
                }
            }
        }
    }
}
