/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {
    void main() {
        Scanner entrada = new Scanner(System.in);

        int[][] matrizNum = new int[9][9];

        // contador auxiliar
        int linhaMatriz = 0;

        System.out.println("Matriz original: ");

        // lê o arquivo
        while (entrada.hasNext()) {
            String linha = entrada.nextLine();
            System.out.println(linha);

            // armazena o conteúdo do arquivo em uma matriz de inteiros
            for (int i = 0; i < linha.length(); i++) {
                matrizNum[linhaMatriz][i] = linha.charAt(i) == '.' ? 0 : 9; // se for '.', armazena 0, caso contrário,
                                                                            // armazena '1'
            }

            linhaMatriz++;
        }

        System.out.println("Matriz campo: ");

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                // se for asterisco
                if (matrizNum[i][j] == 9) {
                    for (int i2 = i - 1; i2 < i + 1; i2++) {

                        for (int j2 = j - 1; j2 < j + 1; j2++) {
                            if (i2 >= 0 && i2 < 9 && j2 >= 0 && j2 < 9) {
                                if (matrizNum[i2][j2] != 9) {
                                    matrizNum[i2][j2]++;
                                }
                            }
                        }
                    }
                }
            }
        }

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                if(matrizNum[i][j] == 9) System.out.print("*");
                else System.out.print(matrizNum[i][j]);
            }
            System.out.println();
        }

        entrada.close();
    }
}