/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class AsciiArt {
    void main(String[] args){
        if(args.length == 3){

            int linhas = Integer.parseInt(args[1]);
            int colunas = Integer.parseInt(args[2]);

            switch (args[0].toLowerCase()){
                case "triângulo":
                    for (int i = 0; i <= linhas; i++) {
                        System.out.println("*".repeat(i));
                    }
                    break;

                case "losango":
                    int metade = linhas / 2;

                    break;

                case "retangulo":
                    for (int i = 0; i <= linhas; i++) {

                    }

                case "secreto":
                    String imagem = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡇⠀⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⠟⠀⣀⣠⠄⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⢠⣶⣿⠟⠁⢠⣾⠋⠁⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠹⣿⡇⠀⠀⠸⣿⡄⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠀⠙⠷⡀⠀⠀⢹⠗⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⢀⣤⣴⡖⠒⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠒⢶⣄\n" +
                                    "⠀⠀⠈⠙⢛⣻⠿⠿⠿⠟⠛⠛⠛⠋⠉⠀⠀⠀⣸⡿\n" +
                                    "⠀⠀⠀⠀⠛⠿⣷⣶⣶⣶⣶⣾⠿⠗⠂⠀⢀⠴⠛⠁\n" +
                                    "⠀⠀⠀⠀⠀⢰⣿⣦⣤⣤⣤⣴⣶⣶⠄⠀⠀⠀⠀⠀\n" +
                                    "⣀⣤⡤⠄⠀⠀⠈⠉⠉⠉⠉⠉⠀⠀⠀⠀⢀⡀⠀⠀\n" +
                                    "⠻⣿⣦⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣴⠾⠃⠀⢀\n" +
                                    "⠀⠀⠈⠉⠛⠛⠛⠛⠛⠛⠛⠛⠋⠉⠁⠀⣀⣤⡶⠋\n" +
                                    "⠀⠀⠀⠀⠐⠒⠀⠠⠤⠤⠤⠶⠶⠚⠛⠛⠉⠀⠀⠀";

                    System.out.println(imagem);
                    break;

                default:
                    System.out.println("Figura inválida.\nOpções: Triângulo - Losango - Retângulo - Secreto");
            }

        } else {
            System.out.println("Quantidade incorreta de argumentos.\nArgumentos esperados: 3.\nPrograma encerrado");
        }
    }
}
