/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class AsciiArt {
    void main(String[] args){
    if(args.length == 3){

            int linhas = Integer.parseInt(args[1]);
            int colunas = Integer.parseInt(args[2]);

            switch (args[0].toLowerCase()){
                case "triângulo", "triangulo":
                    for (int i = 0; i <= linhas; i++) {
                        System.out.println("*".repeat(i));
                    }
                    break;

                case "losango":

                    if (linhas % 2 != 0) {
                        int metade = linhas / 2 + 1;

                    for (int i = 1; i <= linhas; i++) {
                        int espacos = Math.abs(metade - i);
                        int asteriscos = Math.abs(linhas - (2 * espacos));

                        System.out.print(" ".repeat(espacos));
                        System.out.println("*".repeat(asteriscos));
                    }
                    } else System.out.println("ERRO: O losango precisa ter tamanho ímpar.");
                    
                    break;

                case "retângulo", "retangulo":
                    System.out.println("*".repeat(linhas));
                    for (int i = 0; i < colunas - 2; i++) {
                        System.out.println("*" + " ".repeat(linhas - 2) + "*");;
                    }
                    System.out.println("*".repeat(linhas));
                    
                    break;

                case "secreto":
                    String imagem = "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡇⠀⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⠟⠀⣀⣠⠄⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⢠⣶⣿⠟⠁⢠⣾⠋⠁⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠹⣿⡇⠀⠀⠸⣿⡄⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⠀⠀⠀⠀⠀⠙⠷⡀⠀⠀⢹⠗⠀⠀⠀⠀⠀⠀\n" +
                                    "⠀⠀⢀⣤⣴⡖⠒⠀⠀⠀⠀⠀⠀⠀⠀⡀⠀⠒⢶⣄\n" +
                                    "⠀⠀⠈⠙⢛⣻⠿⠿⠿⠟⠛⠛⠛⠋⠉⠀⠀⠀⣸⡿\n" +
                                    "⠀⠀⠀⠀⠛⠿⣷⣶⣶⣶⣶⣾⠿⠗⠂⠀⢀⠴⠛⠁\n" +
                                    "⠀⠀⠀⠀⠀⢰⣿⣦⣤⣤⣤⣴⣶⣶⠄⠀⠀⠀⠀⠀\n" +
                                    "⣀⣤⡤⠄⠀⠀⠈⠉⠉⠉⠉⠉⠀⠀⠀⠀⢀⡀⠀⠀\n" +
                                    "⠻⣿⣦⣄⣀⣀⣀⣀⣀⣀⣀⣀⣀⣀⣠⣴⠾⠃⠀⢀\n" +
                                    "⠀⠀⠈⠉⠛⠛⠛⠛⠛⠛⠛⠛⠋⠉⠁⠀⣀⣤⡶⠋\n" +
                                    "⠀⠀⠀⠀⠐⠒⠀⠠⠤⠤⠤⠶⠶⠚⠛⠛⠉⠀⠀⠀";

                    System.out.println(imagem);
                    break;

                default:
                    System.out.println("Figura inválida.\nOpções: Triângulo - Losango - Retângulo - Secreto");
            }

        } else {
            System.out.println("Quantidade incorreta de argumentos.\nArgumentos esperados: 3.\nPrograma encerrado");
        }
    }
}
