/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.awt.Color;
import java.util.concurrent.TimeUnit;

import edu.princeton.cs.algs4.Draw;

public class App {
    public static void main(String[] args) throws InterruptedException {


        
    }
}
