/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Random;

public class App {

    public static void main(String[] args) {

        // // primeira parte da aula

//        System.out.println("Olá, mundo!");
//
//        int ano = 2025;
//
//        for (int i = 0; i < 5; i++) {
//            System.out.println(i);
//        }
//
//        ano++;
//
//        System.out.println("Fim do programa!: " + ano);

        // // segunda parte da aula

//        int ano = 2025;
//
//        System.out.println(ano++);
//        System.out.println(++ano);

        // terceira parte da aula

        Random r = new Random(123456);

        int numero = 0;

//        for (int i = 0; i < 5; i++) {
//            numero = r.nextInt();
//            System.out.println(numero);
//        }

//        for (int i = 0; i < 5; i++) {
//            numero = r.nextInt(10);
//            System.out.println(numero);
//        }

//        for (int i = 0; i < 5; i++) {
//            numero = r.nextInt(0, 10);
//            System.out.println(numero);
//        }

       // // quarta parte da aula

//        String a = "POO";
//        String b = "ifsc";
//
////        int i = 0, j = 1;
////        if (i == 1){};
//
//        if(a.equals(b)){
//            System.out.println("iguais");
//        } else {
//            System.out.println("diferentes");
//        }
//
//        if(a.equalsIgnoreCase("poo")){
//            System.out.println("iguais");
//        } else {
//            System.out.println("diferentes");
//        }
//
//        char c = a.charAt(0);
//        System.out.println(c);
//
//        String d = "Eng" + "enharia " + b + " " + a;
//        System.out.println(d);

//        // quinta parte da aula
//
//        //JavaJavaJava.....
//
//        for (int i = 0; i < 100; i++) {
//            System.out.print("Java");
//        }
//
//        String s = "Java".repeat(100);
//        System.out.println(s);
//

        // sexta parte da aula

        if(args.length == 2){
            System.out.println("Bom dia, " + args[0] + "!" + " Estamos na aula de " + args[1] + ".");
        } else {
            System.out.println("Quantidade incorreta de argumentos.\nArgumentos esperados: 2.\nPrograma encerrado.");
        }
    }

}
