/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Random;

public class App {
    void main(){
        Random r = new Random();

        int numero = r.nextInt(1, 101);

        int tentativas = 1;

        int palpite;

        do{
            palpite = Integer.parseInt(IO.readln("Entre com o seu palpite: "));
            if (palpite > numero) System.out.println("O número sorteado é menor!");
            else System.out.println("O número sorteado é maior!");
            tentativas ++;
        } while(palpite != numero);

        System.out.println("Parabéns, você acertou!");
        System.out.println("Quantidade de tentativas: " + tentativas);
    }
}
