/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.Random;

public class App {
    private ArrayList<Conta> contas = new ArrayList<>();

    private void menu() {
        System.out.println("|---- BANCO ----|");
        System.out.println("1. Criar conta");
        System.out.println("2. Listar contas");
        System.out.println("3. Sacar");
        System.out.println("4. Depositar");
        System.out.println("5. Sair");
        System.out.print("\nEscolha uma opção: ");
    }

    void main() {
        // ArrayList<String> lista = new ArrayList<>(); // Coleção<tipo> var = new
        // Coleção<String>();
        // // mesmo que var lista = new ArrayList<String>();

        // var s = "Yan"; // var é inferência
        // var i = 1; // ele identifica o tipo da variável

        // lista.add("Juca");
        // lista.add(s);
        // lista.add("Maria");
        // lista.add("Pedro");

        // String nome = lista.get(i);
        // System.out.println("Nome na posição 1: ");
        // System.out.println(nome);

        // lista.add(1, "João");

        // nome = lista.get(i);
        // System.out.println("\nNome na posição 1: ");
        // System.out.println(nome);

        // System.out.println("\nTamanho da lista: ");
        // System.out.println(lista.size());

        // System.out.println("\nCom for i só imprimindo 'Maria': ");
        // for (int j = 0; j < lista.size() - 1; j++) {
        // if (lista.get(j) == "Maria") {
        // System.out.println(lista.get(j));
        // }
        // }

        // System.out.println("\nCom for each: ");
        // // é preferível percorrer em for each
        // for (String elemento : lista) {
        // System.out.println(elemento);
        // }

        // System.out.println("\nCom lista.forEach: ");
        // // outra forma de percorrer e imprimir os elementos
        // lista.forEach(elemento -> System.out.println(elemento)); // => var ->
        // sout(var);

        // System.out.println("\nCom expressão lambda só imprimindo 'Maria'");
        // lista.forEach(a -> {
        // if(a.equals("Maria")){
        // System.out.println(a);
        // }
        // });

        // System.out.println("\nCom method reference: ");
        // lista.forEach(IO::println);

        // // remover Maria
        // lista.removeIf(elemento -> elemento.equals("Maria"));
        // System.out.println("\nRemovendo Maria: ");
        // lista.forEach(IO::println);

        // Menu com 5 opções
        // 1 - Criar conta
        // 2 - Listar todas contas
        // 3 - Depósito
        // 4 - Saque
        // 5 - Sair

        App app = new App();
        int opcao;

        do {
            app.menu();
            opcao = Integer.parseInt(IO.readln());
            switch (opcao) {
                case 1:
                    String titular = IO.readln("Entre com o nome do titular: ");
                    Random r = new Random();

                    long numConta = r.nextInt(1000, 20000);

                    double saldo = Double.parseDouble(IO.readln("Entre com o saldo inicial: "));

                    Conta conta = new Conta(numConta, saldo, titular);

                    contas.add(conta);
                    break;

                case 2:
                    contas.forEach(IO::println);

                case 3:
                    long n = Long.parseLong(IO.readln("Entre com o número da conta: "));
                    double valor = Double.parseDouble(IO.readln("Entre com o valor a depositar: "));

                    contas.forEach(e ->{
                        if (e.getNumConta() == n){
                            if(e.depositar(valor)){
                                System.out.println("Depósito realizado com sucesso!");
                                break;
                            } System.out.println("Não foi possível depositar.");
                            break;
                        }
                    });
                    break;

                default:
                    break;
            }
        } while (opcao != 5);
    }
}