/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {

    void main(String[] args) {
        int dia = Integer.parseInt(IO.readln("Entre com o dia: "));
        String mes = IO.readln("Entre com o mês: ");

        if (dia < 1 || dia > 31){
            dia = Integer.parseInt(IO.readln("Dia inválido, tente novamente: "));
        }

        String estacao;

        switch (mes.toLowerCase()){

            case "janeiro", "fevereiro" : estacao = "verão";
                break;

            case "março":
                if(dia < 20) estacao = "verão";
                else estacao = "outono";
                break;

            case "abril", "maio" : estacao = "outono";
                break;

            case "junho":
                if(dia < 21) estacao = "outono";
                else estacao = "inverno";
                break;

            case "julho", "agosto" : estacao = "inverno";
                break;

            case "setembro":
                if (dia < 23) estacao = "inverno";
                else estacao = "primavera";
                break;

        }
    }
}
