/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.Random;

public class App {
    private ArrayList<Conta> contas = new ArrayList<>();

    private void menu() {
        System.out.println("|---- BANCO ----|");
        System.out.println("1. Criar conta");
        System.out.println("2. Listar contas");
        System.out.println("3. Sacar");
        System.out.println("4. Depositar");
        System.out.println("5. Sair");
        System.out.print("\nEscolha uma opção: ");
    }

    void main() {
        App app = new App();
        int opcao;

        do {
            app.menu();
            opcao = Integer.parseInt(IO.readln());
            switch (opcao) {
                case 1:
                    String titular = IO.readln("Entre com o nome do titular: ");
                    Random r = new Random();

                    long numConta = r.nextInt(1000, 20000);

                    double saldo = Double.parseDouble(IO.readln("Entre com o saldo inicial: "));

                    Conta conta = new Conta(numConta, saldo, titular);

                    contas.add(conta);
                    break;

                case 2:
                    contas.forEach(IO::println);
                    break;

                case 3:
                    long nContaS = Long.parseLong(IO.readln("Entre com o número da conta: "));
                    double valorSaque = Double.parseDouble(IO.readln("Entre com o valor a sacar: "));

                    contas.forEach(e -> {
                        if (e.getNumConta() == nContaS) {
                            if (e.sacar(valorSaque)) {
                                System.out.println("Saque realizado com sucesso!");
                            } else
                                System.out.println("Não foi possível sacar.");
                        }
                    });
                    break;

                case 4:
                    long nContaD = Long.parseLong(IO.readln("Entre com o número da conta: "));
                    double valorDeposito = Double.parseDouble(IO.readln("Entre com o valor a depositar: "));

                    contas.forEach(e -> {
                        if (e.getNumConta() == nContaD) {
                            if (e.depositar(valorDeposito)) {
                                System.out.println("Depósito realizado com sucesso!");
                            } else {
                                System.out.println("Não foi possível depositar.");
                            }
                        }
                    });
                    break;

                case 5:
                    System.out.println("Encerrando...");
                    break;

                default:
                    break;
            }
        } while (opcao != 5);
    }
}