/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {
    /*
     * 1. Cadastrar livro
     * 2. Listar ISBN e título de todos os livros
     * 3. Consultar livro por ISBN e imprimir os dados do livro
     * 4. Consultar livro por autor e imprimir os dados do(s) livro(s)
     * 5. Atualizar dados de um livro, esxeto o ISBN
     * 6. Remover um livro pelo ISBN
     * 7. Sair
     */
    private HashMap<String, Livro> acervo = new HashMap<>();

    private void menu() {
        System.out.println("|--- BIBLIOTECA ---|");
        System.out.println("1. Cadastrar livro");
        System.out.println("2. Listar livros");
        System.out.println("3. Consultar por ISBN");
        System.out.println("4. Consultar por autor");
        System.out.println("5. Atualizar livro");
        System.out.println("6. Remover livro:");
        System.out.println("7. Sair");
    }

    private void cadastrar() {
        String iSBN = IO.readln("Entre com o ISBN: ");

        if (acervo.containsKey(iSBN)) {
            System.out.println("ISBN já cadastrado, retornando ao menu...");
            return;
        }

        String titulo = IO.readln("Entre com o título: ");
        String autor = IO.readln("Entre com o nome do autor: ");
        int anoPublicacao = Integer.parseInt(IO.readln("Entre com o ano de publicação: "));

        Livro livro = new Livro(iSBN, titulo, autor, anoPublicacao);

        acervo.put(iSBN, livro);
    }

    private void listarLivros() {
        for (Livro livro : acervo.values()) {
            System.out.println("==================");
            System.out.println(livro);
        }
    }

    private void consultarISBN() {
        String iSBN = IO.readln("Entre com o ISBN: ");

        Livro livro = acervo.get(iSBN);

        if (!livro.equals(null)) {
            System.out.println(livro);
        }
    }

    private void consultarAutor() {
        String autor = IO.readln("Entre com o nome do autor: ");

        for (Livro livro : acervo.values()) {
            if (livro.getAutor().equalsIgnoreCase(autor)) {
                if (!livro.equals(null)) {
                    System.out.println(livro);
                }
            }
        }
    }

    private void atualizarLivro() {
        String iSBN = IO.readln("Entre com o ISBN: ");

        Livro livro = acervo.get(iSBN);

        if (livro == null) {
            System.out.println("Livro não encontrado, retornando...");
            return;
        }

        System.out.println("""
                Alterar título?
                1. Sim
                2. Não
                """);

        int escolha = Integer.parseInt(IO.readln("\nSua escolha: "));

        if (escolha == 1) {
            String titulo = IO.readln("\nEntre com o novo título: ");
            livro.setTitulo(titulo);
        }

        System.out.println("""

                Alterar autor?
                1. Sim
                2. Não
                """);

        escolha = Integer.parseInt(IO.readln("\nSua escolha: "));

        if (escolha == 1) {
            String autor = IO.readln("\nEntre com o novo autor: ");
            livro.setAutor(autor);
        }

        System.out.println("""

                Alterar ano de publicação?
                1. Sim
                2. Não
                """);

        escolha = Integer.parseInt(IO.readln("\nSua escolha: "));

        if (escolha == 1) {
            int anoPublicacao = Integer.parseInt(IO.readln("\nEntre com o novo ano de publicação: "));
            livro.setAnoPublicacao(anoPublicacao);
        }
    }

    private void removerLivro() {
        String iSBN = IO.readln("\nEntre com o ISBN: ");

        Livro livro = acervo.get(iSBN);

        if (livro == null) {
            System.out.println("Livro não encontrado, retornando...");
            return;
        }

        acervo.remove(iSBN);
    }

    void main() {

        App app = new App();

        Livro a = new Livro("948", "Java", "Deitel", 2001);
        Livro b = new Livro("12345", "The Paladin Prophecy", "Mark Frost", 2012);
        Livro c = new Livro("65843", "Mais Esperto Que o Diabo", "Napoleon Hill", 1938);

        if (!app.acervo.containsKey(a.getISBN())) {
            app.acervo.put(a.getISBN(), a);
        }

        if (!app.acervo.containsKey(b.getISBN())) {
            app.acervo.put(b.getISBN(), b);
        }

        if (!app.acervo.containsKey(c.getISBN())) {
            app.acervo.put(c.getISBN(), c);
        }

        // percorrendo chave e valor
        app.acervo.forEach((key, value) -> {
            System.out.println(String.format("chave: %s\n|--- livro ---|\n%s", key, value));
        });

        // percorrendo apenas valor
        for (Livro livro : app.acervo.values()) {
            System.out.println(livro);
        }

        int opcao;

        do {
            app.menu();
            opcao = Integer.parseInt(IO.readln("Escolha uma opção: "));

            switch (opcao) {
                case 1:
                    app.cadastrar();
                    break;

                case 2:
                    app.listarLivros();
                    break;

                case 3:
                    app.consultarISBN();
                    break;

                case 4:
                    app.consultarAutor();
                    break;

                case 5:
                    app.atualizarLivro();
                    break;

                case 6:
                    app.removerLivro();
                    break;

                default:
                    break;
            }
        } while (opcao != 7);
    }
}