/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.awt.Color;
import java.util.concurrent.TimeUnit;

import edu.princeton.cs.algs4.Draw;

public class App {
    public static void main(String[] args) throws InterruptedException {

        Draw draw = new Draw();

        draw.setXscale(0, 800);
        draw.setYscale(0, 800);
        draw.setCanvasSize(800, 800);

        draw.rectangle(150, 700, 100, 50);

        draw.setPenColor(Color.RED);

        draw.filledCircle(400, 400, 250);

        draw.setPenColor(Color.BLACK);

        draw.filledCircle(400, 400, 30);

        draw.circle(400, 400, 150);

        draw.filledCircle(400, 400, 50); // central

        draw.filledCircle(400, 550, 30); // superior
        draw.filledCircle(275, 320, 30); // direita
        draw.filledCircle(525, 320, 30); // esquerda

        

        // double x[] = { 100, 200, 300, 220 };
        // double y[] = { 100, 200, 400, 530 };

        // draw.polygon(x, y);

        // draw.text(400, 400, "POO");

        // draw.enableDoubleBuffering();

        // for (int i = 0; i < 10; i++){
        //     draw.clear();
        //     draw.text(400, 400, "" + i);
        //     draw.show();
        //     TimeUnit.SECONDS.sleep(1);
        // }
    
        // draw.setPenColor(Color.LIGHT_GRAY);
        // for (int i = 0; i < 800; i+=50){
        //     draw.line(i, 0, i, 800);
        //     draw.line(0, i, 800, i);
        // }

        // draw.show();
    }
}
